# This is a basic GitHub Action YML test file to test your Hello, World! output

name: Generate Test Report 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [push, workflow_dispatch]

env:
  parent_repo: 'css-143-test/CSS143_YoungHumanV2_Tests'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  analysis:
    name: CheckStyle
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.parent_repo }}
          #token: ${{ secrets.TOKEN }}
      - uses: actions/checkout@v2
        with:
          path: student
      - run: find student/ -name \*.java -exec cp {} src/main/java/ \;
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8        
      #- name: Run Google Code Analysis Here
      #  run: java com.puppycrawl.tools.checkstyle.Main -c docs/google_checks.xml src/
      - uses: dbelyaev/action-checkstyle@v0.1.1
        with:
          checkstyle_config: google_checks.xml
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check, github-check, github-pr-review].
          reporter: github-check
          # Change reporter level if you need [info,warning,error].
          # GitHub Status Check won't become failure with a warning.
          level: warning
          workdir: src/main
 
  build:
    # The type of runner that the job will run on
    name: Build Step
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.parent_repo }}
          #token: ${{ secrets.TOKEN }}
      - uses: actions/checkout@v2
        with:
          path: student
      - run: find student/ -name \*.java -exec cp {} src/main/java/ \;
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt
      - name: Build with Maven
        run:  mvn clean compile test --batch-mode --fail-at-end
      - name: Run Test Report
        if:   ${{ always() }}
        run:  python3 testreport.py TextAnalysisTest.java scores.txt
      - name: Publish Test Report
        if:   ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  misspell: # this checks spelling in comments
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.parent_repo }}
          #token: ${{ secrets.TOKEN }}
      - uses: actions/checkout@v2
        with:
          path: student
      - run: find student/ -name \*.java -exec cp {} src/main/java/ \;
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          locale: "US"
          path: src/main
